# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Familog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'MessageKit'
  pod 'Protobuf', :inhibit_warnings => true
  pod 'SDWebImage', '~> 5.0'
  pod 'IQKeyboardManagerSwift','~> 6.5.0'
  pod 'YPImagePicker'
  pod 'ProgressHUD'
  pod 'Lightbox'
  # Pods for Familog

  target 'FamilogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FamilogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
