# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'monologue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for monologue
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Protobuf', :inhibit_warnings => true
  target 'monologueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'monologueUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
